Data Ingestion: Load the first 50,000 rows of Reviews.csv using pandas.


In [7]:
import pandas as pd

df = pd.read_csv("Reviews.csv", nrows=50000)

print(df.head())
print(df.shape)

   Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1 

Text Selection: Create a list containing exactly three specific text strings where the
word &quot;light&quot; is used in different contexts:
o Sentence 1: A review where &quot;light&quot; means low-calorie, weight, or texture
(e.g., &quot;This olive oil is wonderful and very light on the stomach.&quot;).
o Sentence 2: A review where &quot;light&quot; means illumination or physical visibility
(e.g., &quot;The packaging was broken and let too much light inside the box.&quot;).
o Sentence 3: Another review where &quot;light&quot; matches the low-calorie or weight
context of Sentence 1 (e.g., &quot;I prefer this brand because it is a light and
healthy snack.&quot;).

In [8]:
light_reviews = df[df["Text"].str.contains("light", case=False, na=False)]

print(light_reviews["Text"].head(50))

2      This is a confection that has been around a fe...
5      I got a wild hair for taffy and ordered this f...
54     I roast at home with a stove-top popcorn poppe...
64     This product serves me well as a source of ele...
94     This is the same food we get at pet store. But...
101    Arrived slightly thawed. My parents wouldn't a...
178    This is not as good as the Frozen Lemon juice,...
189    The coffee is very finely processed and the fl...
221    I've tried a variety of Ahmad tea. Not because...
238    A very delicate green tea with a smooth light ...
246    I love love love this deal - it's way fun to p...
263    I have used and liked Sugar in the Raw for man...
269    This is a delicious sugar. It has a pretty lig...
286    Nothing wrong with the product, but I sure had...
299    I first found Steaz Berry Energy Shots at a lo...
303    I use this product daily, and it provides a st...
304    I've been buying and drinking this for over a ...
327    Even though we are Inter

In [9]:
sentence1 = "This olive oil is wonderful and very light on the stomach."
sentence2 = "The packaging was broken and let too much light inside the box."
sentence3 = "I prefer this brand because it is a light and healthy snack."

In [10]:
sentences = [sentence1, sentence2, sentence3]

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

matrix = vectorizer.fit_transform(sentences)

In [12]:
dense_matrix = matrix.toarray()

print(dense_matrix)

[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [13]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

In [14]:
print(vec_1)
print(vec_2)
print(vec_3)

[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
[1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
[1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [15]:
import numpy as np

similarity_12 = np.dot(vec_1, vec_2)

similarity_13 = np.dot(vec_1, vec_3)

In [16]:
print("Similarity between Sentence 1 and Sentence 2:")
print(similarity_12)

print()

print("Similarity between Sentence 1 and Sentence 3:")
print(similarity_13)

Similarity between Sentence 1 and Sentence 2:
4

Similarity between Sentence 1 and Sentence 3:
4
